### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by iceaway** [Snipet-ir/Snippet2#41]
Hi! 

This looks like a very interesting project, but I have so far not managed to get it started. I cloned the repo and tried to get it up and running using `docker-compose up -d`, which worked, but when I go to the web page I am unable to login/sign up. I'm suspecting that this is because the database is not correctly set up (looks like it by the look of the logs). There is no database service defined in the docker-compose file, I'm guessing the issue lies here. Is there any guide on how to get started that I have managed to miss?

**Comment by ehcaning** [comment]
Thanks for opening this issue, and sorry for late reply.
Yes, good catch, I will fix it in the following PR. 🍾
